-- ============================================================================
-- 01_grants.sql
-- Access controls: BI_READER can see MARTS_FINANCE and the masked email
-- column only — it never gets RAW, STAGING, or unmasked PII. FINANCE_ADMIN
-- is the only role granted the "unmask" privilege used by macros/mask_pii.sql
-- in production. Run after 00_setup_database_warehouse.sql.
-- ============================================================================

USE ROLE SECURITYADMIN;

-- Ingestion: write-only into RAW
GRANT USAGE ON DATABASE PAYMENTS_LEDGER TO ROLE PAYMENTS_LOADER;
GRANT USAGE ON SCHEMA PAYMENTS_LEDGER.RAW TO ROLE PAYMENTS_LOADER;
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA PAYMENTS_LEDGER.RAW TO ROLE PAYMENTS_LOADER;
GRANT USAGE ON WAREHOUSE WH_PAYMENTS_LOAD TO ROLE PAYMENTS_LOADER;

-- dbt: read RAW, write STAGING/SNAPSHOTS/MARTS
GRANT USAGE ON DATABASE PAYMENTS_LEDGER TO ROLE DBT_TRANSFORMER;
GRANT USAGE ON SCHEMA PAYMENTS_LEDGER.RAW TO ROLE DBT_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PAYMENTS_LEDGER.RAW TO ROLE DBT_TRANSFORMER;
GRANT ALL ON SCHEMA PAYMENTS_LEDGER.STAGING TO ROLE DBT_TRANSFORMER;
GRANT ALL ON SCHEMA PAYMENTS_LEDGER.SNAPSHOTS TO ROLE DBT_TRANSFORMER;
GRANT ALL ON SCHEMA PAYMENTS_LEDGER.INTERMEDIATE TO ROLE DBT_TRANSFORMER;
GRANT ALL ON SCHEMA PAYMENTS_LEDGER.MARTS_CORE TO ROLE DBT_TRANSFORMER;
GRANT ALL ON SCHEMA PAYMENTS_LEDGER.MARTS_LEDGER TO ROLE DBT_TRANSFORMER;
GRANT ALL ON SCHEMA PAYMENTS_LEDGER.MARTS_FINANCE TO ROLE DBT_TRANSFORMER;
GRANT USAGE ON WAREHOUSE WH_DBT_TRANSFORM TO ROLE DBT_TRANSFORMER;

-- BI / Metabase: read-only on the semantic layer, nothing upstream of it
GRANT USAGE ON DATABASE PAYMENTS_LEDGER TO ROLE BI_READER;
GRANT USAGE ON SCHEMA PAYMENTS_LEDGER.MARTS_CORE TO ROLE BI_READER;
GRANT USAGE ON SCHEMA PAYMENTS_LEDGER.MARTS_FINANCE TO ROLE BI_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PAYMENTS_LEDGER.MARTS_CORE TO ROLE BI_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PAYMENTS_LEDGER.MARTS_FINANCE TO ROLE BI_READER;
GRANT USAGE ON WAREHOUSE WH_BI_QUERY TO ROLE BI_READER;

-- Finance leadership: everything BI_READER gets, plus the ledger mart
GRANT ROLE BI_READER TO ROLE FINANCE_ADMIN;
GRANT USAGE ON SCHEMA PAYMENTS_LEDGER.MARTS_LEDGER TO ROLE FINANCE_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PAYMENTS_LEDGER.MARTS_LEDGER TO ROLE FINANCE_ADMIN;
